import Head from 'next/head';
import Link from 'next/link';

import * as themes from '../models/themes.json';
import { setToLS } from '../util/storage/LocalStorage';
import styles from '../styles/Home.module.scss';
import { useEffect } from 'react';

export default function Home() {
    useEffect(() => {
        setToLS('all-themes', themes.default);
    });

    return (
        <div>
            <Head>
                <title>huyy</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles['home-container']}>
                <h1>huyy.</h1>
                <Link href="/projects/quote-generator">Quote generator</Link>
                <Link href="/projects/infinite-scroll">Infinite scroll</Link>
                <Link href="/projects/stream-lab">Stream lab</Link>
                <Link href="/projects/story-teller">Story teller</Link>
                <Link href="/projects/theme">Theme selector</Link>
            </main>

            <footer></footer>
        </div>
    );
}
