import Head from 'next/head';
import Link from 'next/link';

import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div>
      <Head>
        <title>huyy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles['home-container']}>
        <h1>Huy Dang.</h1>
        
        <Link href="https://talofapass.as.gov/">
          TalofaPASS (contributor)
        </Link>
        <Link href="#">
          GuruAcademy - Online teaching system like Udemy (In progess) (NextJs + Redux + Thunk + Nodejs + Mongoose)
        </Link>
        <Link href="https://huydang-blog.vercel.app/">
          Blog - FE (NextJs + Typescript + NextAuth + TailwindCSS + Recoil + Sanity studio)
        </Link>
        <Link href="https://huyblog.sanity.studio/">
          Blog - BE (Not public)
        </Link>
        <Link href="/projects/quote-generator">Quote generator (React)</Link>
        <Link href="https://react-timer-delta.vercel.app/">Basic dynamic timer (React)</Link>
        <Link href="/projects/infinite-scroll">Infinite scroll (React + Unflash API)</Link>
        <Link href="/projects/stream-lab">Stream lab (React + WebRTC) (uncomplete)</Link>
        <Link href="/projects/story-teller">Story teller (React + Voicerss API)</Link>
        <Link href="https://todo-list-nine-sandy.vercel.app/">
          Advanced TodoList - (Random account to login) (React)
        </Link>
        <Link href="/projects/theme">Theme selector (NextJs)</Link>
        <Link href="/projects/motion">Motion - Animation (NextJs)</Link>
      </main>

      <footer></footer>
    </div>
  );
}
